name: CI

on:
  push:
    branches:
      - main
      - '**/pr-*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          # adjust for your test command:
          pytest --maxfail=1 --disable-warnings -q

      - name: Lint code
        run: |
          # adjust if you use flake8/black/etc.
          flake8 .
